export const mockedCharts: any = {
  '39392': {
    id: 39392,
    chartAlert: null,
    chartStatus: 'rendered',
    chartStackTrace: null,
    chartUpdateEndTime: 1737060918938,
    chartUpdateStartTime: 1737060915688,
    latestQueryFormData: {
      datasource: '222__table',
      viz_type: 'dist_bar',
      slice_id: 39392,
      url_params: {
        dash_url: 'http://localhost:3000/dash/2rZBhHbTynt0YjUyEcGOBIvXWyt',
        native_filters_key:
          'NvzZ0FDLXMt82T_-kCVfneNM_yaC53i-AlvaJg74qcZcO1MLS2rZbSKfv6z6WF7e',
        times: '1737060161162',
      },
      metrics: [
        {
          aggregate: 'SUM',
          column: {
            column_name: 'na_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 883,
            is_dttm: false,
            optionName: '_col_NA_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'North America',
          optionName: 'metric_a943v7wg5g_0mm03hrsmpf',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'eu_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 884,
            is_dttm: false,
            optionName: '_col_EU_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Europe',
          optionName: 'metric_bibau54x0rb_dwrjtqkbyso',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'jp_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 885,
            is_dttm: false,
            optionName: '_col_JP_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Japan',
          optionName: 'metric_06whpr2oyhw_4l88xxu6zvd',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'other_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 886,
            is_dttm: false,
            optionName: '_col_Other_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Other',
          optionName: 'metric_pcx05ioxums_ibr16zvi74',
          sqlExpression: null,
        },
      ],
      adhoc_filters: [
        {
          clause: 'WHERE',
          comparator: '10',
          expressionType: 'SIMPLE',
          filterOptionName: 'filter_juemdnqji5_d6fm8tuf4rc',
          isExtra: false,
          isNew: false,
          operator: '<=',
          sqlExpression: null,
          subject: 'rank',
        },
      ],
      groupby: ['name'],
      columns: [],
      row_limit: null,
      order_desc: true,
      contribution: true,
      color_scheme: 'supersetColors',
      show_legend: true,
      rich_tooltip: true,
      bar_stacked: true,
      y_axis_format: 'SMART_NUMBER',
      y_axis_bounds: [null, null],
      bottom_margin: 'auto',
      x_ticks_layout: 'staggered',
      annotation_layers: [],
      granularity_sqla: 'year',
      queryFields: {
        columns: 'groupby',
        groupby: 'groupby',
        metrics: 'metrics',
      },
      time_range: 'No filter',
      shared_label_colors: {
        count: '#454E7C',
        'North America': '#1FA8C9',
        Europe: '#5AC189',
        Japan: '#666666',
        Other: '#FCC700',
      },
      extra_filters: [],
      extra_form_data: {},
      dashboardId: 14,
    },
    sliceFormData: null,
    queryController: {},
    queriesResponse: [
      {
        cache_key: 'fb613475920a678b916c55a39b039fa1',
        cached_dttm: null,
        cache_timeout: 300,
        errors: [],
        form_data: {
          datasource: '222__table',
          viz_type: 'dist_bar',
          slice_id: 39392,
          url_params: {
            dash_url: 'http://localhost:3000/dash/2rZBhHbTynt0YjUyEcGOBIvXWyt',
            native_filters_key:
              'NvzZ0FDLXMt82T_-kCVfneNM_yaC53i-AlvaJg74qcZcO1MLS2rZbSKfv6z6WF7e',
            times: '1737060161162',
          },
          metrics: [
            {
              aggregate: 'SUM',
              column: {
                column_name: 'na_sales',
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 883,
                is_dttm: false,
                optionName: '_col_NA_Sales',
                python_date_format: null,
                type: 'DOUBLE PRECISION',
                verbose_name: null,
              },
              expressionType: 'SIMPLE',
              hasCustomLabel: true,
              isNew: false,
              label: 'North America',
              optionName: 'metric_a943v7wg5g_0mm03hrsmpf',
              sqlExpression: null,
            },
            {
              aggregate: 'SUM',
              column: {
                column_name: 'eu_sales',
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 884,
                is_dttm: false,
                optionName: '_col_EU_Sales',
                python_date_format: null,
                type: 'DOUBLE PRECISION',
                verbose_name: null,
              },
              expressionType: 'SIMPLE',
              hasCustomLabel: true,
              isNew: false,
              label: 'Europe',
              optionName: 'metric_bibau54x0rb_dwrjtqkbyso',
              sqlExpression: null,
            },
            {
              aggregate: 'SUM',
              column: {
                column_name: 'jp_sales',
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 885,
                is_dttm: false,
                optionName: '_col_JP_Sales',
                python_date_format: null,
                type: 'DOUBLE PRECISION',
                verbose_name: null,
              },
              expressionType: 'SIMPLE',
              hasCustomLabel: true,
              isNew: false,
              label: 'Japan',
              optionName: 'metric_06whpr2oyhw_4l88xxu6zvd',
              sqlExpression: null,
            },
            {
              aggregate: 'SUM',
              column: {
                column_name: 'other_sales',
                description: null,
                expression: null,
                filterable: true,
                groupby: true,
                id: 886,
                is_dttm: false,
                optionName: '_col_Other_Sales',
                python_date_format: null,
                type: 'DOUBLE PRECISION',
                verbose_name: null,
              },
              expressionType: 'SIMPLE',
              hasCustomLabel: true,
              isNew: false,
              label: 'Other',
              optionName: 'metric_pcx05ioxums_ibr16zvi74',
              sqlExpression: null,
            },
          ],
          adhoc_filters: [
            {
              clause: 'WHERE',
              comparator: '10',
              expressionType: 'SIMPLE',
              filterOptionName: 'filter_juemdnqji5_d6fm8tuf4rc',
              isExtra: false,
              isNew: false,
              operator: '<=',
              sqlExpression: null,
              subject: 'rank',
            },
          ],
          groupby: ['name'],
          columns: [],
          row_limit: null,
          order_desc: true,
          contribution: true,
          color_scheme: 'supersetColors',
          show_legend: true,
          rich_tooltip: true,
          bar_stacked: true,
          y_axis_format: 'SMART_NUMBER',
          y_axis_bounds: [null, null],
          bottom_margin: 'auto',
          x_ticks_layout: 'staggered',
          annotation_layers: [],
          granularity_sqla: 'year',
          queryFields: {
            columns: 'groupby',
            groupby: 'groupby',
            metrics: 'metrics',
          },
          time_range: 'No filter',
          shared_label_colors: {
            count: '#454E7C',
            'North America': '#1FA8C9',
            Europe: '#5AC189',
            Japan: '#666666',
            Other: '#FCC700',
          },
          dashboardId: 14,
          applied_time_extras: {},
          where: '',
          having: '',
          filters: [
            {
              col: 'rank',
              op: '<=',
              val: '10',
            },
          ],
        },
        is_cached: false,
        query:
          'SELECT name AS name,\n       sum(na_sales) AS "North America",\n       sum(eu_sales) AS "Europe",\n       sum(jp_sales) AS "Japan",\n       sum(other_sales) AS "Other"\nFROM public.video_game_sales\nWHERE rank <= 10\nGROUP BY name\nORDER BY "North America" DESC\nLIMIT 50000',
        from_dttm: null,
        to_dttm: null,
        status: 'success',
        stacktrace: null,
        rowcount: 10,
        colnames: ['name', 'North America', 'Europe', 'Japan', 'Other'],
        coltypes: [1, 0, 0, 0, 0],
        data: [
          {
            key: 'North America',
            values: [
              {
                x: 'Wii Sports',
                y: 0.5014503263234228,
              },
              {
                x: 'Super Mario Bros.',
                y: 0.7226640159045725,
              },
              {
                x: 'Duck Hunt',
                y: 0.9512539738608266,
              },
              {
                x: 'Tetris',
                y: 0.7666886979510906,
              },
              {
                x: 'Mario Kart Wii',
                y: 0.44236673178900354,
              },
              {
                x: 'Wii Sports Resort',
                y: 0.4772727272727273,
              },
              {
                x: 'New Super Mario Bros. Wii',
                y: 0.5099615519049283,
              },
              {
                x: 'Wii Play',
                y: 0.4836263357462944,
              },
              {
                x: 'New Super Mario Bros.',
                y: 0.3792069310229924,
              },
              {
                x: 'Pokemon Red/Pokemon Blue',
                y: 0.3591459528362014,
              },
            ],
          },
          {
            key: 'Europe',
            values: [
              {
                x: 'Wii Sports',
                y: 0.3507372492144065,
              },
              {
                x: 'Super Mario Bros.',
                y: 0.0889662027833002,
              },
              {
                x: 'Duck Hunt',
                y: 0.022253620628753093,
              },
              {
                x: 'Tetris',
                y: 0.07468605419695969,
              },
              {
                x: 'Mario Kart Wii',
                y: 0.35947530002790956,
              },
              {
                x: 'Wii Sports Resort',
                y: 0.3336363636363636,
              },
              {
                x: 'New Super Mario Bros. Wii',
                y: 0.24676686473261097,
              },
              {
                x: 'Wii Play',
                y: 0.31713202344019303,
              },
              {
                x: 'New Super Mario Bros.',
                y: 0.30756414528490506,
              },
              {
                x: 'Pokemon Red/Pokemon Blue',
                y: 0.28330146590184835,
              },
            ],
          },
          {
            key: 'Japan',
            values: [
              {
                x: 'Wii Sports',
                y: 0.04556441866086536,
              },
              {
                x: 'Super Mario Bros.',
                y: 0.169234592445328,
              },
              {
                x: 'Duck Hunt',
                y: 0.009890498057223597,
              },
              {
                x: 'Tetris',
                y: 0.1394580304031725,
              },
              {
                x: 'Mario Kart Wii',
                y: 0.1057772816075914,
              },
              {
                x: 'Wii Sports Resort',
                y: 0.09939393939393938,
              },
              {
                x: 'New Super Mario Bros. Wii',
                y: 0.16427822439706397,
              },
              {
                x: 'Wii Play',
                y: 0.10099965529127888,
              },
              {
                x: 'New Super Mario Bros.',
                y: 0.21659446851049652,
              },
              {
                x: 'Pokemon Red/Pokemon Blue',
                y: 0.32568514977692803,
              },
            ],
          },
          {
            key: 'Other',
            values: [
              {
                x: 'Wii Sports',
                y: 0.10224800580130529,
              },
              {
                x: 'Super Mario Bros.',
                y: 0.019135188866799203,
              },
              {
                x: 'Duck Hunt',
                y: 0.01660190745319675,
              },
              {
                x: 'Tetris',
                y: 0.019167217448777262,
              },
              {
                x: 'Mario Kart Wii',
                y: 0.09238068657549538,
              },
              {
                x: 'Wii Sports Resort',
                y: 0.08969696969696969,
              },
              {
                x: 'New Super Mario Bros. Wii',
                y: 0.0789933589653967,
              },
              {
                x: 'Wii Play',
                y: 0.09824198552223372,
              },
              {
                x: 'New Super Mario Bros.',
                y: 0.09663445518160614,
              },
              {
                x: 'Pokemon Red/Pokemon Blue',
                y: 0.03186743148502231,
              },
            ],
          },
        ],
        applied_filters: [
          {
            column: 'rank',
          },
        ],
        rejected_filters: [],
      },
    ],
    triggerQuery: false,
    lastRendered: 0,
    form_data: {
      datasource: '222__table',
      viz_type: 'dist_bar',
      slice_id: 39392,
      url_params: {
        dash_url: 'http://localhost:3000/dash/2rZBhHbTynt0YjUyEcGOBIvXWyt',
        native_filters_key:
          'NvzZ0FDLXMt82T_-kCVfneNM_yaC53i-AlvaJg74qcZcO1MLS2rZbSKfv6z6WF7e',
        times: '1737060161162',
      },
      metrics: [
        {
          aggregate: 'SUM',
          column: {
            column_name: 'na_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 883,
            is_dttm: false,
            optionName: '_col_NA_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'North America',
          optionName: 'metric_a943v7wg5g_0mm03hrsmpf',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'eu_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 884,
            is_dttm: false,
            optionName: '_col_EU_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Europe',
          optionName: 'metric_bibau54x0rb_dwrjtqkbyso',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'jp_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 885,
            is_dttm: false,
            optionName: '_col_JP_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Japan',
          optionName: 'metric_06whpr2oyhw_4l88xxu6zvd',
          sqlExpression: null,
        },
        {
          aggregate: 'SUM',
          column: {
            column_name: 'other_sales',
            description: null,
            expression: null,
            filterable: true,
            groupby: true,
            id: 886,
            is_dttm: false,
            optionName: '_col_Other_Sales',
            python_date_format: null,
            type: 'DOUBLE PRECISION',
            verbose_name: null,
          },
          expressionType: 'SIMPLE',
          hasCustomLabel: true,
          isNew: false,
          label: 'Other',
          optionName: 'metric_pcx05ioxums_ibr16zvi74',
          sqlExpression: null,
        },
      ],
      adhoc_filters: [
        {
          clause: 'WHERE',
          comparator: '10',
          expressionType: 'SIMPLE',
          filterOptionName: 'filter_juemdnqji5_d6fm8tuf4rc',
          isExtra: false,
          isNew: false,
          operator: '<=',
          sqlExpression: null,
          subject: 'rank',
        },
      ],
      groupby: ['name'],
      columns: [],
      row_limit: null,
      order_desc: true,
      contribution: true,
      color_scheme: 'supersetColors',
      show_legend: true,
      rich_tooltip: true,
      bar_stacked: true,
      y_axis_format: 'SMART_NUMBER',
      y_axis_bounds: [null, null],
      bottom_margin: 'auto',
      x_ticks_layout: 'staggered',
      annotation_layers: [],
      granularity_sqla: 'year',
      label_colors: {},
      queryFields: {
        columns: 'groupby',
        groupby: 'groupby',
        metrics: 'metrics',
      },
      time_range: 'No filter',
    },
    name: 'Top 10 Games: Proportion of Sales in Markets',
  },
  '96': {
    id: 96,
    chartAlert: null,
    chartStatus: 'rendered',
    chartStackTrace: null,
    chartUpdateEndTime: 1737060917947,
    chartUpdateStartTime: 1737060915656,
    latestQueryFormData: {
      datasource: '22__table',
      viz_type: 'treemap_v2',
      slice_id: 96,
      url_params: {
        preselect_filters:
          '{"1389": {"platform": ["PS", "PS2", "PS3", "PS4"], "genre": null, "__time_range": "No filter"}}',
        dash_url: 'http://localhost:3000/dash/2rZBhHbTynt0YjUyEcGOBIvXWyt',
        native_filters_key:
          'NvzZ0FDLXMt82T_-kCVfneNM_yaC53i-AlvaJg74qcZcO1MLS2rZbSKfv6z6WF7e',
        times: '1737060161162',
      },
      groupby: ['genre'],
      metric: 'count',
      row_limit: null,
      adhoc_filters: [],
      color_scheme: 'supersetColors',
      show_labels: true,
      show_upper_labels: true,
      label_type: 'key_value',
      number_format: 'SMART_NUMBER',
      date_format: 'smart_date',
      annotation_layers: [],
      granularity_sqla: 'year',
      label_colors: {},
      queryFields: {
        groupby: 'groupby',
        metrics: 'metrics',
      },
      time_range: 'No filter',
      treemap_ratio: 1.618033988749895,
      shared_label_colors: {
        count: '#454E7C',
        'North America': '#1FA8C9',
        Europe: '#5AC189',
        Japan: '#666666',
        Other: '#FCC700',
      },
      extra_filters: [],
      extra_form_data: {},
      dashboardId: 14,
    },
    sliceFormData: null,
    queryController: {},
    queriesResponse: [
      {
        cache_key: 'c91093871f90049f4bc9b0eacd0eed80',
        cached_dttm: null,
        cache_timeout: 300,
        applied_template_filters: [],
        annotation_data: {},
        error: null,
        is_cached: null,
        query:
          'SELECT genre AS genre,\n       COUNT(*) AS count\nFROM public.video_game_sales\nGROUP BY genre\nLIMIT 50000;\n\n',
        status: 'success',
        stacktrace: null,
        rowcount: 12,
        from_dttm: null,
        to_dttm: null,
        label_map: {
          genre: ['genre'],
          count: ['count'],
        },
        colnames: ['genre', 'count'],
        indexnames: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        coltypes: [1, 0],
        data: [
          {
            genre: 'Adventure',
            count: 1286,
          },
          {
            genre: 'Puzzle',
            count: 582,
          },
          {
            genre: 'Strategy',
            count: 681,
          },
          {
            genre: 'Role-Playing',
            count: 1487,
          },
          {
            genre: 'Simulation',
            count: 866,
          },
          {
            genre: 'Misc',
            count: 1739,
          },
          {
            genre: 'Fighting',
            count: 848,
          },
          {
            genre: 'Racing',
            count: 1249,
          },
          {
            genre: 'Sports',
            count: 2346,
          },
          {
            genre: 'Action',
            count: 3315,
          },
          {
            genre: 'Shooter',
            count: 1310,
          },
          {
            genre: 'Platform',
            count: 886,
          },
        ],
        result_format: 'json',
        applied_filters: [],
        rejected_filters: [],
      },
    ],
    triggerQuery: false,
    lastRendered: 0,
    form_data: {
      datasource: '22__table',
      viz_type: 'treemap_v2',
      slice_id: 96,
      url_params: {
        preselect_filters:
          '{"1389": {"platform": ["PS", "PS2", "PS3", "PS4"], "genre": null, "__time_range": "No filter"}}',
        dash_url: 'http://localhost:3000/dash/2rZBhHbTynt0YjUyEcGOBIvXWyt',
        native_filters_key:
          'NvzZ0FDLXMt82T_-kCVfneNM_yaC53i-AlvaJg74qcZcO1MLS2rZbSKfv6z6WF7e',
        times: '1737060161162',
      },
      groupby: ['genre'],
      metric: 'count',
      row_limit: null,
      adhoc_filters: [],
      color_scheme: 'supersetColors',
      show_labels: true,
      show_upper_labels: true,
      label_type: 'key_value',
      number_format: 'SMART_NUMBER',
      date_format: 'smart_date',
      annotation_layers: [],
      granularity_sqla: 'year',
      label_colors: {
        '0': '#1FA8C9',
        '1': '#454E7C',
        '2600': '#666666',
        '3DO': '#B2B2B2',
        '3DS': '#D1C6BC',
        Action: '#1FA8C9',
        Adventure: '#454E7C',
        DC: '#A38F79',
        DS: '#8FD3E4',
        Europe: '#5AC189',
        Fighting: '#5AC189',
        GB: '#FDE380',
        GBA: '#ACE1C4',
        GC: '#5AC189',
        GEN: '#3CCCCB',
        GG: '#EFA1AA',
        Japan: '#FF7F44',
        'Microsoft Game Studios': '#D1C6BC',
        Misc: '#FF7F44',
        N64: '#1FA8C9',
        NES: '#9EE5E5',
        NG: '#A1A6BD',
        Nintendo: '#D3B3DA',
        'North America': '#666666',
        Other: '#E04355',
        PC: '#EFA1AA',
        PCFX: '#FDE380',
        PS: '#A1A6BD',
        PS2: '#FCC700',
        PS3: '#3CCCCB',
        PS4: '#B2B2B2',
        PSP: '#FEC0A1',
        PSV: '#FCC700',
        Platform: '#666666',
        Puzzle: '#E04355',
        Racing: '#FCC700',
        'Role-Playing': '#A868B7',
        SAT: '#A868B7',
        SCD: '#8FD3E4',
        SNES: '#454E7C',
        Shooter: '#3CCCCB',
        Simulation: '#A38F79',
        Sports: '#8FD3E4',
        Strategy: '#A1A6BD',
        TG16: '#FEC0A1',
        'Take-Two Interactive': '#9EE5E5',
        WS: '#ACE1C4',
        Wii: '#A38F79',
        WiiU: '#E04355',
        X360: '#A868B7',
        XB: '#D3B3DA',
        XOne: '#FF7F44',
      },
      queryFields: {
        groupby: 'groupby',
        metrics: 'metrics',
      },
      time_range: 'No filter',
      treemap_ratio: 1.618033988749895,
    },
    name: 'Games per Genre',
  },
};
